export interface DraftMessage {
  role: "customer" | "agent";
  body: string;
}

export interface DraftContext {
  channel: string;
  subject?: string | null;
  contactName?: string | null;
  orgName?: string;
  messages: DraftMessage[];
}

export interface DraftResult {
  text: string;
  /** true when generated by a live LLM provider; false = deterministic fallback. */
  live: boolean;
}

/** Whether a live AI provider is configured (Anthropic). */
export function aiConfigured(): boolean {
  return process.env.AI_PROVIDER === "anthropic" && Boolean(process.env.ANTHROPIC_API_KEY);
}

/** Deterministic, clearly-useful fallback when no provider key is set. */
function deterministicDraft(ctx: DraftContext): string {
  const name = ctx.contactName?.split(" ")[0];
  const greeting = name ? `Hi ${name},` : "Hi there,";
  return `${greeting}

Thanks for reaching out — I'd be happy to help with this. I've reviewed your message and I'm looking into it now. To make sure I get this exactly right, could you confirm any relevant details (such as an order number or the email on your account)?

I'll follow up shortly with the next steps.

Best regards,
${ctx.orgName ?? "Support"}`;
}

/**
 * Generates a suggested agent reply. Uses the Anthropic API when configured
 * (AI_PROVIDER=anthropic + ANTHROPIC_API_KEY), otherwise returns a deterministic
 * draft so the feature works end-to-end without a provider. The model is
 * configurable via AI_MODEL (default claude-opus-5); set it to claude-haiku-4-5
 * or claude-sonnet-5 for cheaper/faster drafts.
 */
export async function generateReplyDraft(ctx: DraftContext): Promise<DraftResult> {
  if (!aiConfigured()) {
    return { text: deterministicDraft(ctx), live: false };
  }

  try {
    const { default: Anthropic } = await import("@anthropic-ai/sdk");
    // Org-scoped keys need a workspace id header; workspace-scoped keys don't.
    const workspaceId = process.env.ANTHROPIC_WORKSPACE_ID;
    const client = new Anthropic(
      workspaceId ? { defaultHeaders: { "anthropic-workspace-id": workspaceId } } : {},
    );
    const model = process.env.AI_MODEL || "claude-opus-5";

    const org = ctx.orgName ?? "our company";
    const system =
      `You are a helpful, concise customer-support agent for ${org}. ` +
      `Draft the agent's next reply to the customer's most recent message. ` +
      `Be warm, professional and specific. Do NOT invent policies, prices, order numbers, ` +
      `dates, or any facts that are not present in the conversation — if key information is ` +
      `missing, ask a brief clarifying question instead. Keep it under about 120 words. ` +
      `Output only the reply text, with no preamble, labels, or quotation marks.`;

    const convo = ctx.messages
      .map((m) => `${m.role === "customer" ? "Customer" : "Agent"}: ${m.body}`)
      .join("\n");
    const user =
      `Channel: ${ctx.channel}\n` +
      (ctx.subject ? `Subject: ${ctx.subject}\n` : "") +
      (ctx.contactName ? `Customer name: ${ctx.contactName}\n` : "") +
      `\nConversation so far:\n${convo}\n\nWrite the agent's next reply.`;

    const res = await client.messages.create({
      model,
      max_tokens: 1024,
      output_config: { effort: "low" },
      system,
      messages: [{ role: "user", content: user }],
    });

    const text = res.content
      .map((b) => (b.type === "text" ? b.text : ""))
      .join("\n")
      .trim();

    return text ? { text, live: true } : { text: deterministicDraft(ctx), live: false };
  } catch {
    // Any provider/network error → fall back so the agent still gets a draft.
    return { text: deterministicDraft(ctx), live: false };
  }
}
